### ISSUE TITLE
Error when stashing file on split set

### ISSUE THREAD

**Issue by ths84** [UB-Mannheim/GTCheck#11]
If I stash a line on a split gt set, I get the following error (adding, commiting and skipping works fine):

`git.exc.GitCommandError
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rm -f /home/thschmidt/GTCheck/gtcheck/static/subrepo/c92654aac0d3a6d8e15ca965a9caafb4203f44fecb8b36f62235c3158b8b63da/duplicate_02_part_01/gtlines/001_0001.gt.txt
  stderr: 'fatal: pathspec '/home/thschmidt/GTCheck/gtcheck/static/subrepo/c92654aac0d3a6d8e15ca965a9caafb4203f44fecb8b36f62235c3158b8b63da/duplicate_02_part_01/gtlines/001_0001.gt.txt' did not match any files'
Traceback (most recent call last):
  File "/home/thschmidt/GTCheck/venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/thschmidt/GTCheck/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/thschmidt/GTCheck/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thschmidt/GTCheck/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thschmidt/GTCheck/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thschmidt/GTCheck/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/thschmidt/GTCheck/gtcheck/app.py", line 369, in edit
    repo.git.rm('-f', str(fname))
  File "/home/thschmidt/GTCheck/venv/lib/python3.7/site-packages/git/cmd.py", line 584, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/thschmidt/GTCheck/venv/lib/python3.7/site-packages/git/cmd.py", line 1120, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/thschmidt/GTCheck/venv/lib/python3.7/site-packages/git/cmd.py", line 924, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rm -f /home/thschmidt/GTCheck/gtcheck/static/subrepo/c92654aac0d3a6d8e15ca965a9caafb4203f44fecb8b36f62235c3158b8b63da/duplicate_02_part_01/gtlines/001_0001.gt.txt
  stderr: 'fatal: pathspec '/home/thschmidt/GTCheck/gtcheck/static/subrepo/c92654aac0d3a6d8e15ca965a9caafb4203f44fecb8b36f62235c3158b8b63da/duplicate_02_part_01/gtlines/001_0001.gt.txt' did not match any files'`

I checked the metioned folder and file (_/home/thschmidt/GTCheck/gtcheck/static/subrepo/c92654aac0d3a6d8e15ca965a9caafb4203f44fecb8b36f62235c3158b8b63da/duplicate_02_part_01/gtlines/001_0001.gt.txt_), which exists.

**Comment by JKamlah** [comment]
This issue is now fixed in the multiuser_keying_webversion branch and will be merged to the main branch soon.
