### ISSUE TITLE
NoneType object no attribute data_stream

### ISSUE THREAD

**Issue by M3ssman** [UB-Mannheim/GTCheck#8]
#### Issue description

Open a folder with tif and txt files fails on Ubuntu 20.04 using default Python 3.8.5 and Firefox with TIFFViewer Addon

#### Steps to reproduce the issue

1. Setup folder with about 300 pairs with images + text 
2. Only images already committed, all text files untracked due future corrections.
3. Clone repository, setup venv, install dependencies via pip
4. Start: `gtcheck <path-to-repo>` 
5. Review start page: looks fine
6. Click green button "Start" 

#### What's the expected result?
- Open View with Images and Text

#### What's the actual result?
- Werkzeug Error screen

#### Additional details / screenshot
```
127.0.0.1 - - [11/Jun/2021 10:13:50] "POST /gtcheckinit HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/hartwig/Projekte/work/mlu/ulb/github-gtcheck/venv/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hartwig/Projekte/work/mlu/ulb/github-gtcheck/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/hartwig/Projekte/work/mlu/ulb/github-gtcheck/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hartwig/Projekte/work/mlu/ulb/github-gtcheck/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hartwig/Projekte/work/mlu/ulb/github-gtcheck/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hartwig/Projekte/work/mlu/ulb/github-gtcheck/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/hartwig/Projekte/work/mlu/ulb/github-gtcheck/gtcheck/app.py", line 341, in gtcheckinit
    return gtcheck()
  File "/home/hartwig/Projekte/work/mlu/ulb/github-gtcheck/gtcheck/app.py", line 172, in gtcheck
    origtext = item.a_blob.data_stream.read().decode('utf-8').lstrip(" ")
AttributeError: 'NoneType' object has no attribute 'data_stream'

```

# Reproduce

Maybe an issue with Python Version

**Comment by JKamlah** [comment]
@M3ssman thank you for the feedback.
We will fix the issue soon.

**Comment by JKamlah** [comment]
We have now pushed a complete rework of GTCheck. The described problem is solved. Please notice that the readme needs an update, please use gtcheck.py --help for further information. I will close the issue, when the rework is done.
